---
url: https://esphome.io/
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
hassio_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 0
panel_icon: mdi:chip
uart: true
ports:
  6052/tcp: 6052
map:
  - ssl:ro
  - config:rw
discovery:
  - esphome
schema:
  status_use_ping: bool?
  streamer_mode: bool?
  home_assistant_dashboard_integration: bool?
  default_compile_process_limit: int(1,)?
  ssl: bool?
  certfile: str?
  keyfile: str?
  leave_front_door_open: bool?
backup_exclude:
  - '*/*/'
init: false
startup: services

name: ESPHome (2024.6 pinned)
panel_title: ESPHome 2024.6
version: 2024.6.0
slug: esphome_2024_6
description: ESPHome dashboard pinned to version 2024.6.0
image: ghcr.io/esphome/esphome-hassio-{arch}

